-- mydbユーザーを作成する

CREATE USER mydb IDENTIFIED BY app;

GRANT CREATE SESSION TO mydb;
GRANT CREATE TABLE TO mydb;
GRANT RESOURCE TO mydb;
GRANT UNLIMITED TABLESPACE TO mydb;

-- 修正時刻: Wed Jan 27 13:25:35 2021
